api/urls.py
from django.urls import path, include

from rest_framework import routers, permissions
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from rest_framework_simplejwt.views import TokenVerifyView

from api import views

from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
   openapi.Info(
      title="Sensoriando API",
      default_version='beta',
      description="-= description =-",
      #terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="noBots@sensoriando.com.br"),
      license=openapi.License(name="copyright Sensoriando@2023"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)

#router = routers.DefaultRouter()

urlpatterns = [
    path('', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),

    path('data/stats/private/', views.PrivateStatisticsViewSets.as_view(), name='PrivateStatistics'),
    path('data/detail/', views.PublicDetailViewSets.as_view(), name='PublicDetailThingSensor'),
    path('data/detail/private', views.PrivateDetailViewSets.as_view(), name='PrivateDetailThingSensor'),
    
    path('accounts/', views.PublicAccountViewSets.as_view({'get': 'list'}), name='PublicAccount'),
    #path('account/private/', views.PrivateAccountViewSets.as_view({'get': 'list'}), name='PrivateAccount'),
    #path('account/thing/', views.AccountThingViewSets.as_view({'get': 'list'}), name='ThingsAccount'),
    #path('account/thing/tag/', views.AccountThingSensorTagView.as_view(), name='TagThingAccount'),
    
    path('things/', views.PublicThingsViewSets.as_view(), name='PublicThings'),
    path('things/private/', views.PrivateThingsViewSets.as_view(), name='PrivateThings'),
    #path('things/', views.ThingViewSets.as_view({'get': 'list'}), name='ListThings'),
    #path('things/tags/', views.ThingTagViewSets.as_view({'get': 'list'}), name='TagsThings'),
    path('sensors/', views.SensorViewSets.as_view({'get': 'list'}), name='ListSensors'),
    path('sensors/tags/', views.PublicSensorTagViewSets.as_view({'get': 'list'}), name='TagsSensors'),

    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),

]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

from base import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('', include('overview.urls')),
    path('users/', include('users.urls')),
    path('www/', views.RedirectSensoriando, name='www'),
    path('thing/', include('sensors.urls')),

]

sensors/urls.py
from django.urls import path, include
from sensors import views

#https://learndjango.com/tutorials/django-login-and-logout-tutorial
urlpatterns = [
    path('detail/<str:uuid>', views.ThingDetails, name='thingdetail'),

]

users/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views

from users import views

app_name = 'users'

#https://learndjango.com/tutorials/django-login-and-logout-tutorial
urlpatterns = [
    path('signup/', views.SignUp, name='signup'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', views.SignIn.as_view(), name='login'),
    path('account/<str:username>/<str:tab>', views.MyAccount, name='account'),
]

web/web/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

sensors/models.py
from django.db import models

# Create your models here.

sensors/views.py
from django.conf import settings
from django.shortcuts import render, redirect
from django.http import HttpResponse

from base.views import callAPI
from users.views import check_and_refresh_token
from base.models import ThingsModel, AccountsModel, PlansModel, ThingsSensorsModel, ThingsTagsModel, SensorsUnitsModel

from dateutil.parser import parse
import pandas as pd
import json

def ThingDetails(request, uuid = None):
    defaults = {
        "charttype": 'line',
        "chartview": "second",
 
    }

    dateFormats = {
        'second': {'label': '%d/%m/%Y %H:%M', 'legend': '%S'},
        'minute': {'label': '%d/%m/%Y %Hh', 'legend': '%M'},
        'hour': {'label': '%d/%m/%Y', 'legend': '%H'},
        'day': {'label': '%m/%Y', 'legend': '%d'},
        'month': {'label': '%Y', 'legend': '%m'},
        'year': {'label': '', 'legend': '%Y'},

    }

    chartView = defaults['chartview']

    # Get data
    thing = ThingsModel.objects.get(uuid = uuid)
    thingtags = ThingsTagsModel.objects.filter(id_thing = thing.id)
    thingssensors = ThingsSensorsModel.objects.filter(id_thing = thing.id)
    account = AccountsModel.objects.get(accountsthings__id_thing = thing.id)
 
    tags = []
    for tag in thingtags:
        tags.append(tag.name)

    sensors = []
    for thingsensor in thingssensors:
        id_sensor = thingsensor.id_sensor_id
        sensor = thingsensor.id_sensor.name
        sensor_unit = SensorsUnitsModel.objects.get(isdefault = True, id_sensor = id_sensor)

        defaults["chartunit"] = sensor_unit
        defaults["chartprecision"] = sensor_unit.precision
 
        # Get from cookies
        try:
            chartView = request.COOKIES.get('chartview')

            if not chartView:
                chartView = defaults['chartview']
        except:
            chartView = defaults['chartview']

        try:
            chartType = request.COOKIES.get('chart' + str(id_sensor))

            if not chartType:
                chartType = defaults['charttype']
        except:
            chartType = defaults['charttype']
    
        try:
            chartPrecision = int(request.COOKIES.get('precision' + str(id_sensor)))
        
            if not chartPrecision:
                chartPrecision = defaults['chartprecision']
        except:
            chartPrecision = defaults['chartprecision']

        try:
            id_unit = request.COOKIES.get('unit' + str(id_sensor))
            chartUnit = SensorsUnitsModel.objects.get(id = id_unit)

            if not chartUnit:
                chartUnit = defaults['chartunit']
        except:
            chartUnit = defaults['chartunit']

        jsonParams = {
            'thing': uuid,
            'sensor': sensor,
            'period': chartView,

        }
    
        if account.id_plan.ispublic:
            jsonResult = callAPI(
                endpoint = "/data/detail/", \
                data = jsonParams, \
                method = "POST"
            )
        else:
            jsonResult = callAPI(
                endpoint = "/data/detail/private/", \
                data = jsonParams, \
                method = "POST", \
                token = check_and_refresh_token()
            )

        # Precisa melhorar isso
        try:
            len(jsonResult)
        except:
            jsonResult = None
        ####

        if jsonResult: 
            lastDatum = parse(jsonResult[-1]['dtread'])
            chartLabel = lastDatum.strftime(dateFormats[chartView]['label'])

            for read in jsonResult:
                dtPart = parse(read['dtread'])
                read['dtread'] = dtPart.strftime(dateFormats[chartView]['legend'])

            #Grouping values
            df = pd.DataFrame(jsonResult)                                   #Panda: Convert json to DataFrame
            df["value"] = df.groupby("dtread")["value"].transform("mean")   #Panda: Calc average
            df.eval("value = " + chartUnit.expression.replace("pv", "value"), \
                    inplace = True)                                         #Panda: Math Expression
            df["value"] = df["value"].round(chartPrecision)
            processedData = df.to_dict("records")                           #Panda: Convert DataFrame to Dict
        
            sensors.append({
                'name': sensor,
                'type': chartType,
                'label': chartLabel,
                'lastdatum': lastDatum,
                'unit': chartUnit,
                'data': processedData,

            })

    context = {
        'thing': thing.name,
        'thing_tags': tags,
        'chart_file': 'chart.js',
        'city': account.city,
        'state': account.state,
        'title': chartView,
        'country': account.country,
        'sensors': sensors,

    }

    return render(request, 'detail.html', {'context': context})

templates/account.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    {% include 'head.html' %}


<script type="text/javascript">
function setCookie(cname, cvalue, exdays) {
    var d = new Date();
    d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));

    var expires = "expires=" + d.toGMTString();
    var cookie = cname + "=" + cvalue + ";" + expires + ";path=/";

    document.cookie = cookie;
}

function getCookie(cname) {
    var name = cname + "=";
    var decodedCookie = decodeURIComponent(document.cookie);
    var ca = decodedCookie.split(';');

    for(var i = 0; i <ca.length; i++) {
        var c = ca[i];
    
        while (c.charAt(0) == ' ') {
            c = c.substring(1);
        }
    
        if (c.indexOf(name) == 0) {
            return c.substring(name.length, c.length);
        }
    }

    return "";
}

function getValue(combobox){
    var cb_name = combobox;
    var selectCtrl = document.getElementById(cb_name);
    var selectedItem =  selectCtrl.options[selectCtrl.selectedIndex];
 
    setCookie(cb_name, selectedItem.value, 365);
}    
</script>

</head>

<body>
    <section class="background">
        <img class="grayscale" src="{% static "img/background.jpeg" %}" alt="technology components">
    </section>

    <header>
        {% include 'header.html' %}
    </header>

    <main>
        <section class="home">
            {% include 'baraccount.html' %}
        </section>

        <section class="account">

 <ul class="nav nav-tabs">    
    <li id="account-profile" {% if form.active == "profile" %}class="active"{% endif %}><span class="nav-link" data-toggle="tab">Perfil</span></li>
    <li id="account-thing" {% if form.active == "things" %}class="active"{% endif %}><span class="nav-link" data-toggle="tab">Centrais</span></li>
    <li id="account-sensor" {% if form.active == "sensors" %}class="active"{% endif %}><span class="nav-link" data-toggle="tab">Sensores</span></li>
</ul>

<div class="tab-content">
    
    <div class={% if form.active == "profile" %}"tab-pane fade in active"{% else %}"tab-pane fade"{% endif %} id="profile">

<form method="post">
  {% csrf_token %}
  <p>
    <label for="{{ form.user.first_name.id_for_label }}" class="font-16px">Nome</label> {{ form.user.first_name }}
    <span class="helptext font-11px">Obrigatório.</span>
  </p>

  <p>
    <label for="{{ form.user.last_name.id_for_label }}" class="font-16px">Sobrenome</label> {{ form.user.last_name }}
    <span class="helptext font-11px">Obrigatório.</span>
  </p>

  <p>
    <label for="{{ form.user.email.id_for_label }}" class="font-16px">{{ form.user.email.label }}</label> {{ form.user.email }}
    <span class="helptext font-11px">Obrigatório que seja um endereço de e-mail válido.</span>
  </p>

  <p>
    <label for="{{ form.profile.city.id_for_label }}" class="font-16px">{{ form.profile.city.label }}</label> {{ form.profile.city }}
    <span class="helptext font-11px">Obrigatório.</span>
  </p>

  <p>
    <label for="{{ form.profile.state.id_for_label }}" class="font-16px">{{ form.profile.state.label }}</label> {{ form.profile.state }}
    <span class="helptext font-11px">Obrigatório.</span>
  </p>

  <p>
    <label for="{{ form.profile.country.id_for_label }}" class="font-16px">{{ form.profile.country.label }}</label> {{ form.profile.country }}
    <span class="helptext font-11px">Obrigatório.</span>
  </p>

  <button name="profileform" type="submit">Alterar</button>

</form>
      
    </div>

    <div class={% if form.active == "things" %}"tab-pane fade in active"{% else %}"tab-pane fade"{% endif %} id="things">
 
<form method="post">
  {% csrf_token %}
  {{ form.thing.as_p }}
  <button name="thingform" type="submit">Adicionar</button>
</form>       

        <table class="table table-striped" >
            <tr>
                <th> Nome </th>
                <th> UUID </th>
                <th> Configurações </th>
            </tr>

{% for thing in form.things %}
            <tr>
                <th> {{ thing.name }} </th>
                <th> {{ thing.uuid }} </th>
                <th>
                    <button name="thingparam{{ thing.id }}" type="button" disabled>Parâmetros</button> 
                </th>
                </th>
            </tr>
{% endfor %}
            
          </table>    
    </div>
    
    <div class={% if form.active == "sensors" %}"tab-pane fade in active"{% else %}"tab-pane fade"{% endif %} id="sensors">
        <table class="table table-striped" >
            <tr>
                <th> Sensores </th>
                <th> Unidade </th>
                <th> Precisão </th>
                <th> Exibição (Gráfico/Widget) </th>
                <th> Configuração </th>
            </tr>

{% for sensor in form.sensors %}
            <tr>
                <th> {{ sensor.name }} </th>

                <th>
                    <select name="unit{{ sensor.id }}" id="unit{{ sensor.id }}">
{% for unit in sensor.units %}
    {% if sensor.unitselect == None and unit.isdefault == True or sensor.unitselect == unit.id %}
    <option value={{ unit.id }} onclick="javascript:getValue('unit{{ sensor.id }}')" selected>{{ unit.name }} {% if unit.initial != None %}({{ unit.initial }}){% endif %}</option>
    {% else %}
    <option value={{ unit.id }} onclick="javascript:getValue('unit{{ sensor.id }}')">{{ unit.name }} {% if unit.initial != None %}({{ unit.initial }}){% endif %}</option>
    {% endif %} 
{% endfor %}
                    </select>

                </th>

                <th>
                    <select name="precision{{ sensor.id }}" id="precision{{ sensor.id }}">
{% for i in form.precision %}
    {% if sensor.precisionselect == i %}
                        <option value={{ i }} onclick="javascript:getValue('precision{{ sensor.id }}')" selected>{{ i }}</option>
    {% else %}
                        <option value={{ i }} onclick="javascript:getValue('precision{{ sensor.id }}')">{{ i }}</option>
    {% endif %}
{% endfor %}
                    </select>
                </th>

                <th>
                    <select name="chart{{ sensor.id }}" id="chart{{ sensor.id }}">
                        <option value="line" onclick="javascript:getValue('chart{{ sensor.id }}')" {% if sensor.chartselect == 'line' %} selected {% endif %}>Linha</option>
                        <option value="bar" onclick="javascript:getValue('chart{{ sensor.id }}')" {% if sensor.chartselect == 'bar' %} selected {% endif %}>Barra Vertical</option>
                        <option value="horizontalBar" onclick="javascript:getValue('chart{{ sensor.id }}')" {% if sensor.chartselect == 'horizontalBar' %} selected {% endif %}>Barra Horizontal</option>
                        <option value="pie" onclick="javascript:getValue('chart{{ sensor.id }}')" {% if sensor.chartselect == 'pie' %} selected {% endif %}>Pizza</option>
                        <option value="table" onclick="javascript:getValue('chart{{ sensor.id }}')" {% if sensor.chartselect == 'table' %} selected {% endif %}>Tabela</option>
                        <option value="display" onclick="javascript:getValue('chart{{ sensor.id }}')" {% if sensor.chartselect == 'display' %} selected {% endif %}>Display</option>
                    </select>
                </th>

                <th>
                    <button name="sensorparam{{ sensor.id }}" type="button" disabled>Parâmetros</button> 
                </th>
            </tr>
{% endfor %}
            
          </table>  
    </div>
</div>


        </section>
    </main>

    <footer>
        {% include 'footer.html' %}
    </footer>
    
</body>

<script type="text/javascript">
  const handleNav = () => {
    const profile = document.getElementById('account-profile');
    const things = document.getElementById('account-thing');
    const sensors = document.getElementById('account-sensor');
    const profileTab = document.getElementById('profile');
    const thingsTab = document.getElementById('things');
    const sensorsTab = document.getElementById('sensors');

    profile.addEventListener('click', () => {
      profile.classList.add('active');
      things.classList.remove('active');
      sensors.classList.remove('active');

      profileTab.classList.add('active');
      thingsTab.classList.remove('active');
      sensorsTab.classList.remove('active');

    });
    things.addEventListener('click', () => {
      profile.classList.remove('active');
      things.classList.add('active');
      sensors.classList.remove('active');

      profileTab.classList.remove('active');
      thingsTab.classList.add('active');
      sensorsTab.classList.remove('active');

    });
    sensors.addEventListener('click', () => {
      profile.classList.remove('active');
      things.classList.remove('active');
      sensors.classList.add('active');

      profileTab.classList.remove('active');
      thingsTab.classList.remove('active');
      sensorsTab.classList.add('active');

    });
  }
  handleNav();
</script>

</html>

templates/baraccount.html
<!-- barAccount.html: BEGIN -->
{% load static %}

<div>
    <h1 class="font-36px">Minha conta</h1>
</div>

<!-- barAccount.html: END -->

templates/bardetail.html
<!-- bardetail.html: BEGIN -->
{% load static %}

<div>
    <h1 class="font-36px">{{ context.thing }}</h1>

        <div class="home-button-list">
            <div class="home-dropdown">
              <button class="font-16px">Visualizar dados</button>
              <div class="home-dropdown-content">
                <a
                  class="font-13px underline-white"
                  href="javascript:setCookie('chartview','second',365);location.reload();"
                  >Segundos</a
                >
                <a
                  class="font-13px underline-white"
                  href="javascript:setCookie('chartview','minute',365);location.reload();"
                  >Minutos</a
                >
                <a
                  class="font-13px underline-white"
                  href="javascript:setCookie('chartview','hour',365);location.reload();"
                  >Horas</a
                >
                <a
                  class="font-13px underline-white"
                  href="javascript:setCookie('chartview','day',365);location.reload();"
                  >Dias</a
                >
                <a
                  class="font-13px underline-white"
                  href="javascript:setCookie('chartview','month',365);location.reload();"
                  >Meses</a
                >
                <a
                  class="font-13px underline-white"
                  href="javascript:setCookie('chartview','year',365);location.reload();"
                  >Anos</a
                >
              </div>
            </div>
            
            <button class="font-16px"><a href="#export">Exportar</a></button>

        </div>
</div>

<!-- bardetail.html: END -->

templates/barfilter.html
<!-- barfilter.html: BEGIN -->
{% load static %}

<div>
    <h1 class="font-36px">Dispositivos</h1>
    
    <button class="font-16px">
        <a href="#filter">Filtros</a>
    </button>
</div>

<!-- barfilter.html: END -->

templates/barsignin.html
<!-- barSignIp.html: BEGIN -->
{% load static %}

<div>
    <h1 class="font-36px">Autenticar usuário</h1>
</div>

<!-- barSignIp.html: END -->

templates/chart.html
<!-- chart.html: BEGIN-->
{% load static %}

<ul>

{% for detail in context.sensors %}
    <li>
        <div> <b>{{ detail.name }}</b> </div>

        <div>
        {% if detail.type == 'table' %}         
            <table height=201 width=100% class="table table-striped">
            <tr>
                <th> Data </th>
                <th> Mensagem </th>
            </tr>

            {% for tablelist in detail.data %}
                <tr>
                    <th>{{ tablelist.dtread }}</th>
                    <th>{{ tablelist.message }}</th>
                </tr>
            {% endfor %}
            </table>

        {% elif detail.type == 'display' %}
            <table height=201 width=100% class="table table-striped">
            <tr>
                <th> {{ detail.unit.name }} </th>
                <th> {{ context.title }} </th>
            </tr>

            <tr>
            {% for displaylist in detail.data %}
                <th> <font size="20"> {{ displaylist.group_value }}</font> {{ detail.unit.initial }} </th>
            {% endfor %}
            </tr>
            
            <tr>
                <th> {{ detail.lastdatum }}</th>
            </tr>
            </table>   

        {% else %}
            <canvas id="ChartDetail{{ forloop.counter }}"></canvas>
        {% endif %}
        </div>        
    </li>
{% endfor %}

</ul>
<!-- chart.html: END-->

templates/footer.html
<!-- footer.html: BEGIN -->
{% load static %}

<div>
    <div class="stats">
        <h3 class="font-22px">Estatisticas</h3>
    </div>

    <div>
        <h3 class="font-22px"></h3>
    </div>
            
    <div>
        <h3 class="font-22px"></h3>
    </div>
</div>

<!-- footer.html: END -->

templates/head.html
<!-- head.html: BEGIN -->
{% load static %}

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Sensoriando: Webservice</title>

<link rel="stylesheet" href="{% static "css/style.css" %}">
<script src="{% static "js/cookies.js" %}"></script>

<!-- head.html: END -->

templates/header.html
<!-- header.html: BEGIN -->
{% load static %}

<nav>
    <a href="/" class="font-27px">Sensoriando</a>
    
    <div class="dropdown">
        <img src="{% static "img/bars.svg" %}" alt="menu icon">
        
        <div class="dropdown-content">
            <a href="/" class="font-16px">Mapa</a>
            <a href="/api" class="font-16px">API</a>

            {% if user.is_authenticated %}
                <a href="/users/account/{{ user.username }}/profile"><span class="glyphicon glyphicon-user"></span>{{ user.username }}</a>
                <button class="font-16px">
                <a href="{% url 'users:logout' %}"><span class="glyphicon glyphicon-log-out"></span>Sair</a>
                </button>

            {% else %}
                <a href="/users/signup"><span class="glyphicon glyphicon-user"></span>Cadastrar</a>
                
                <button class="font-16px">
                <a href="{% url 'users:login' %}"><span class="glyphicon glyphicon-log-in"></span>Entrar</a>
                </button>
            {% endif %}

        </div>
    </div>
    
</nav>

<!-- header.html: END -->

templates/home.html
<!-- templates/home.html-->
{% extends 'common.html' %}

{% block title %}
<title> Web Service: Lista</title>
{% endblock %}

{% block content %}
<script type="text/javascript">
function clearFilter() {
    const jsonString = JSON.stringify('');
 
    var searchSensor = document.getElementById("SearchSensor");
    var searchTag = document.getElementById("SearchTag");

    searchSensor.selectedIndex = 0;
    searchTag.selectedIndex = 0;
    document.cookie = `setFilterHome = ${jsonString}; SameSite=None; secure=True`;
    
    location.reload();
}

function setFilter(key=null, value=null){
    var selectSensor = document.getElementById("SearchSensor");
    var selectTag = document.getElementById("SearchTag");
    var data = {};

    if ( selectSensor ) {
        var SensorItem = selectSensor.options[selectSensor.selectedIndex];
        if (SensorItem.value !== "") {
            data["sensor"] = SensorItem.value;
        }
    }

    if ( selectTag ) {
        var TagItem =  selectTag.options[selectTag.selectedIndex];
        if (TagItem.value !== "") {
            data["sensor_tag"] = TagItem.value;
        }
    }

    if ( key ) {
        data[key] = value;

        if ( key == "sensor" && selectSensor ) {
            selectSensor.value = value;
        }
    }

    if (Object.keys(data).length > 0) {
        const jsonString = JSON.stringify(data);

        document.cookie = `setFilterHome = ${jsonString}; SameSite=None; secure=True`;
        location.reload();
    }
}    
</script>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-9">

{% if request.path == '/home/private' %} 
            <h1>Meus Sensores</h1>
{% else %}
            <h1>Sensores Públicos</h1>
{% endif %}

<!-- Print filter apply -->
            <p>
            {% for key, value in contexts.filterApply.items %}
                {{value}} {%if not forloop.last %}, {% endif %}
            {% endfor %}
            </p>

<!-- Sensors list: BEGIN class="link-no-hover"-->
{% for context in contexts.things %}

<div class="col-md-5 col-sm-6 col-xs-12" data-turbolink="false">
    <div class="panel panel-primary">
        <div class="panel-heading ellipsis">
          <i class="fa fa-bar-chart-o"></i>
          <a class="bg-info text-info" href="/thing/detail/{{ context.uuid }}"><b>{{ context.thing }}</b></a>
        </div>
        
        <div class="panel-body">
            <div class="row">
                <div class="col-sm-6 col-xs-6"><b>Cidade</b></div>
                <div class="col-sm-6 col-xs-6">
                    <a href="#" onclick="setFilter('city', '{{ context.account.city }}');">{{ context.account.city }}</a> /
                    <a href="#" onclick="setFilter('state', '{{ context.account.state }}');">{{ context.account.state }}</a>
                </div>
            </div>
        
            <div class="row">
                <div class="col-sm-6 col-xs-6"><b>País</b></div>
                <div class="col-sm-6 col-xs-6"><a href="#" onclick="setFilter('country', '{{ context.account.country }}');">{{ context.account.country }}</a></div>
            </div> 
 
            <hr style="height:2px;border-width:0;color:gray;background-color:gray">
        
            <div class="public_channel_tags">
                <i class="fa fa-dashboard"></i>

                {% for sensor in context.sensors %}
                    <a href="#" onclick="setFilter('sensor', '{{ sensor.name }}');">{{ sensor.name }}</a>
                {% endfor %}
            </div>

            <div class="row">
                <div class="col-sm-6 col-xs-6"><b>Última leitura</b></div>
                <div class="col-sm-6 col-xs-6">{{ context.lastupdate }}</div>
            </div> 
 
            <hr style="height:2px;border-width:0;color:gray;background-color:gray">
       
            <div class="public_channel_tags">
                <i class="fa fa-tags"></i>
                
                {% for tag in context.thingtags %}
                    <a href="#" onclick="setFilter('thing_tag', '{{ tag.name }}');">{{ tag.name }}</a>     
                {% endfor %}
            </div>
        </div>
    </div>

</div>

{% endfor %}
<!-- Sensors list: END -->


        </div>

{% if request.path == '/home/private' %} 
  <div class="col-xs-12 col-sm-3">

      <h1>Indicadores</h1>

      <div class="col-pad">

          <div class="form-group">
              <label>Plano: </label> {{ contexts.stats.plan }} <br>
              <label>Total de Registros: </label> {{ contexts.stats.records }} {{ contexts.stats.record_unit }} <br>
              <label>Retencao: </label> {{ contexts.stats.retation_current }} de {{ contexts.stats.retation_full }} {{ contexts.stats.retation_unit }}
          </div>

      </div>
  </div>
{% else %}

    <div class="col-xs-12 col-sm-3">

      <h1>Filtros</h1>

      <div class="col-pad">

          <div class="form-group">
            <label for="tag_input"><i class="fa fa-dashboard"></i>&nbsp;</label>
 
            <select name="SearchSensor" id="SearchSensor">
                <option value="" selected>Todos sensores</option>
                {% for sensor in contexts.filters.sensors %}
                <option value={{ sensor.name }}>{{ sensor.name }}</option>
                {% endfor %}
            </select>
          </div>

          <div class="form-group">
            <label for="tag_input"><i class="fa fa-tags"></i>&nbsp;</label>
 
            <select name="SearchTag" id="SearchTag">
                <option value="" selected>Todas tags</option>
                {% for tag in contexts.filters.tags %}
                <option value={{ tag.name }}>{{ tag.name }}</option>
                {% endfor %}
            </select>
          </div>

          <button type="button" id="search" onclick="setFilter();" class="btn btn-primary btn-sm">Aplicar</button>
          <button type="reset" id="clear" onclick="clearFilter();" class="btn btn-primary btn-sm">Limpar</button>

      </div>
  </div>
{% endif %}

    </div>

</div>
{% endblock %}

templates/signin.html
<!-- templates/registration/login.html -->
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    {% include 'head.html' %}
</head>

<body>
    <section class="background">
        <img class="grayscale" src="{% static "img/background.jpeg" %}" alt="technology components">
    </section>

    <header>
        {% include 'header.html' %}
    </header>

    <main>
        <section class="home">
            {% include 'barsignin.html' %}
        </section>

        <section class="signUp">
        <form method="post">
            {% csrf_token %}
            <p><label for="{{ form.username.id_for_label }}" class="font-17px">{{ form.username.label }}</label> {{ form.username }}</p>
            <p><label for="{{ form.password.id_for_label }}" class="font-17px">{{ form.password.label }}</label> {{ form.password }}</p> 
            <button type="submit" class="font-16px"><span>Entrar</span></button>
        </form>
        </section>
    </main>

    <footer>
        {% include 'footer.html' %}
    </footer>
    
</body>

</html>